### PR TITLE
Requirements on Personalization Data

### PR DESCRIPTION
**Pull request by hannestschofenig**
Since we are not really saying what the personalization data is I wonder whether it is necessary to even place any requirements regarding confidentiality on it. Maybe it is fine to have integrity protected personalization data...

### CODE REVIEW

**Comment by dthaler** [comment]
I am ok with the text either with or without this change, I have no preference.  To answer Hannes's question, I believe that previously the term personalization data was meant to refer to things that are specific to a single TEE, and so are encrypted so that only that TEE (and no other TEE) can decrypt it.   If something only requires integrity protection, it doesn't need to be encrypted and so would fall outside the definition of personalization data in the current draft.

**Comment by hannestschofenig** [comment]
I see your logic here. I could imagine that there is a generic binary that needs some configuration data. Some of it might need to be integrity protected while other information also requires confidentiality protection. 

Ming, what do you think?

**Comment by mingpeiwk** [comment]
I think personalization data will be largely confidential to a TEE and also to a TA, basing on the original motivation of this. Therefore encryption support is needed.

**Comment by mingpeiwk** [comment]
On the text change, we can say that personlization data should be encrypted as it is typically confidential data. "may be encrypted" doesn't enforce some recommendation here. As a requirement, the protocol MUST be able to support personalization data encryption.

**Comment by dthaler** [comment]
After discussion in the interim meeting, I think I would prefer not taking this change.

**Review by mingpeiwk — COMMENTED** [review]
Dave has made a change with small edits, describing that "an implementation must support encrypting....". The two context has conflict, and this change doesn't need to be merged. Can we close this PR by removing it? Thanks.

**Pull request closed without merging**
