### PR TITLE
Add brief discussion of confidentiality in protocol

### PR DESCRIPTION
**Pull request by dthaler**
To address point raised by Ming.

For comparison, the corresponding PR for the protocol spec is https://github.com/ietf-teep/teep-protocol/pull/36

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Review by mingpeiwk — COMMENTED** [review]
This section looks good.

We talked about TA binary encryption in the regular section for TAM to TEEP Agent path. I feel that similarly it is worthy to mention the attestation encryption in the TEEP Agent to TAM communication section above.

How do you think?

**Comment by dthaler** [comment]
> We talked about TA binary encryption in the regular section for TAM to TEEP Agent path. I feel that similarly it is worthy to mention the attestation encryption in the TEEP Agent to TAM communication section above.

@mingpeiwk Done, please check https://github.com/ietf-teep/architecture/pull/196/commits/7ac8692be45ae2bf23fa993191cb238b71d39828

**Review by hannestschofenig — APPROVED** [review]
This sounds great

**Comment by mingpeiwk** [comment]
Thanks, it looks good.

**Pull request merged**
